
export CURRENT_BRANCH="production"
export TAG="$CURRENT_BRANCH-${CIRCLE_BUILD_NUM}"

docker build -t $CONTAINER_REGISTRY/$PROJECT_NAME:$TAG -t $CONTAINER_REGISTRY/$PROJECT_NAME:latest .
docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
docker push $CONTAINER_REGISTRY/$PROJECT_NAME